name: qatar_al_nada
description: |
  "شرح قطرالندى" is an educational app designed to provide detailed explanations of classical Arabic texts. 
  It features interactive content with adjustable font sizes, allowing users to customize their reading experience. 
  The app offers a beautiful and user-friendly interface with easy navigation between chapters and a customizable font selection. 
  It also includes quick access to essential features like increasing or decreasing the font size and viewing a privacy policy. 
  Ideal for anyone seeking to learn more about classical Arabic literature in a convenient and accessible format.

version: 2.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.8.0
  flutter_riverpod: ^2.5.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/image.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/img/image.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
   - assets/data.json
   - assets/img/
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/arabic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri.ttf
    - family: Noor
      fonts:
        - asset: assets/fonts/noorehira.ttf
  
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_native_splash:
  color: "#B89B72"  # Background color of splash screen
  image: assets/img/head_drawer.png  # Path to your splash logo image
  android: true
  ios: true
  web: false
  fullscreen: true  # Optional: To make the splash fullscreen