name: qatar_al_nada
description: |
  "شرح قطرالندى" is an educational app designed to provide detailed explanations of classical Arabic texts. 
  It features interactive content with adjustable font sizes, allowing users to customize their reading experience. 
  The app offers a beautiful and user-friendly interface with easy navigation between chapters and a customizable font selection. 
  It also includes quick access to essential features like increasing or decreasing the font size and viewing a privacy policy. 
  Ideal for anyone seeking to learn more about classical Arabic literature in a convenient and accessible format.

version: 2.0.1+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  font_awesome_flutter: ^10.8.0
  # Animation and UI enhancements
  animations: ^2.0.11
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1
  # UI Components
  card_swiper: ^3.0.1
  smooth_page_indicator: ^1.2.0
  flutter_svg: ^2.0.10
  # State Management
  provider: ^6.1.2
  # Utilities
  cached_network_image: ^3.4.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/data.json
   - assets/img/
  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/arabic.ttf
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri.ttf
    - family: Noor
      fonts:
        - asset: assets/fonts/noorehira.ttf
    # Adding Airbnb-style fonts
    # - family: Circular
    #   fonts:
    #     - asset: assets/fonts/circular-regular.ttf
    #     - asset: assets/fonts/circular-medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/circular-bold.ttf
    #       weight: 700

flutter_native_splash:
  color: "#FFFFFF"  # Clean white background like Airbnb
  image: assets/img/splash_logo.png  # Will create a new modern logo
  android: true
  ios: true
  web: false
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/icon.png"